version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

  jobs:
    pre_build:
      - $(pwd | sed "s/checkouts\(\/[^/]\+\)\$/envs\1/")/bin/python -m pip install -e '.[docs]'
      - mkdir -p docs/source/_static

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
  system_packages: false
