name: Compile docs for gh-pages

on:
  push:
    branches: [ main ]

jobs:
  compile-docs:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt -r docs/docs_requirements.txt
        pip install -e .
        pip install pylint
        sudo apt-get install -y graphviz

    - name: Create pylint import graphs
      run: |
        shopt -s globstar
        pylint --rcfile=/dev/null --exit-zero --reports=y --disable=all --enable=imports,RP0402 --int-import-graph=docs/source/int-imports.png src/PROJECT_NAME/**/*.py

    - name: Build docs
      run: cd docs/ && make html && cd ..

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html/
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'compile docs:'
