name: Docstrings

on: [push, pull_request]

jobs:
  docstrings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pydocstyle pytest -r requirements.txt
        pip install pytest-custom_exit_code

    - name: Run pydocstyle
      run: pydocstyle src/ tests/

    - name: Run doctests
      run: pytest --suppress-no-test-exit-code --doctest-modules src/
